<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Is Mike Working Today?</title>
    <style type="text/css">
      html,
      body {
        margin: 0;
        padding: 0;
      }
      body {
        font-size: 20px;
      }
      body.level-4 {
        background-color: rgba(220, 20, 60, 0.25);
      }
      h1 {
        color: green;
        font-size: 4rem;
        margin: 4rem 0;
        padding: 0 1rem;
        text-align: center;
      }
      body.level-2 h1 {
        color: dodgerblue;
      }
      body.level-3 h1,
      body.level-4 h1 {
        color: crimson;
      }
      h2 {
        font-size: 2rem;
        margin-top: 2rem;
        text-align: center;
      }
      h3 {
        font-size: 2rem;
        max-width: 50rem;
        margin: 3rem auto;
        text-align: center;
      }
      p {
        margin: 0 auto;
        max-width: 50rem;
        text-align: center;
        font-size: 1.75rem;
      }
      center {
        margin-top: 4rem;
      }
    </style>
  </head>
  <body class="level-<?php echo $severity; ?>">
    <h2>Is Mike Working Today?</h2>
    <h1><?php echo $status; ?></h1>
    <h3><?php echo $reason; ?></h3>
    <center>
      <small>Last updated: <?php echo $timestamp; ?></small>
    </center>
  </body>
</html>